# Part 1
This Part help us learn about Data Analysis using Pandas Library of Python


Importing File



In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()



Saving california_housing_train.csv to california_housing_train (1).csv


First & Last 5 Rows

In [ ]:
df = pd.read_csv('california_housing_train.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

Data Summary

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
df['total_bedrooms'].unique()

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

In [ ]:
array = df['total_bedrooms'].unique()
array.shape

(1848,)

Data Transformation

In [ ]:
total_bedrooms_per_total_rooms  = df['total_bedrooms']/df['total_rooms']
df = df.assign(total_bedrooms_per_total_rooms = total_bedrooms_per_total_rooms)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.228617  
1                            0.248497  
2                            0.241667  
3                            0.224517  
4                            0.224209  
...                               ...  
16995                        0.177718  
16996                        0.224777  
16997                        0.198356  
16998                        0.206587  
16999                        0.164835  

[17000 rows x 10 columns]

In [ ]:
df['total_bedrooms_per_total_rooms'].mean()


0.21275998821034803

In [ ]:
df['total_bedrooms_per_total_rooms'].std()

0.057823008903161756

Data Filtering

In [ ]:
filt = (df['median_income'] > 5)
df[filt]


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [ ]:
filtered = (df['total_rooms'] > 10000) & (df['median_house_value'] < 150000 )
df.loc[filtered]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [ ]:
df.to_csv('new_california_housing.csv' ,index=False)

# Part 2
This part is about Array Manipulation and usage of Numpy Library

Array Creation And Indexing

In [ ]:
import numpy as np

arr = np.arange(1 , 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(arr[1:19:2])

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
random = np.random.randint(10 , 100 , 20)
rand = random.reshape(5,4)
print(rand)

[[56 12 21 75]
 [49 34 41 65]
 [32 21 96 72]
 [80 56 89 36]
 [30 57 23 65]]


In [ ]:
print(rand[0:3 , 0:2])

[[56 12]
 [49 34]
 [32 21]]


Array Manipulation

In [ ]:
arr = np.arange(20).reshape(5,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
new = arr.flatten()
print(new)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
second = np.arange(32,52)
second = second.reshape(5,4)
matmup = np.multiply(arr , second)
print(matmup)

[[  0  33  68 105]
 [144 185 228 273]
 [320 369 420 473]
 [528 585 644 705]
 [768 833 900 969]]


Boolean And Fancy Indexing

In [ ]:
randomm = np.random.randint(0 , 100 ,50)
randomm = randomm.reshape(10,5)
print(randomm)

[[ 0 95 85 82 79]
 [42 99  0 84 50]
 [55  3 97 26 31]
 [ 1 18 91 41  9]
 [51 68 33 97 38]
 [74 47 75 75 64]
 [40 44 56 98 84]
 [61 63  2 10 74]
 [88 58 98 75 13]
 [38 36 42 30 96]]


In [ ]:
randomm>50

array([[False,  True,  True,  True,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False, False,  True, False, False],
       [ True,  True, False,  True, False],
       [ True, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False,  True]])

In [ ]:
randomm[randomm>50]

array([95, 85, 82, 79, 99, 84, 55, 97, 91, 51, 68, 97, 74, 75, 75, 64, 56,
       98, 84, 61, 63, 74, 88, 58, 98, 75, 96])

In [ ]:
indi = [[0,2]]
randomm[indi]

array([[[ 0, 95, 85, 82, 79],
        [55,  3, 97, 26, 31]]])

Statistical Operation

In [ ]:
for i in range (5) :
  randm = random[i].mean()
  print(randm)

56.0
12.0
21.0
75.0
49.0


In [ ]:
for i in range (5) :
  print(random[i].max())

56
12
21
75
49


In [ ]:
for i in range(5) :
  print(random[i].sum())

56
12
21
75
49


In [ ]:
mask = random>randm

print(random[mask])



[56 75 65 96 72 80 56 89 57 65]


# Part 3
Using Python Basics we can create programs as given below.

In [ ]:
i1 = 0
i2 = 1
sum = 0
for i in range(0 , 100) :
  sum = i1+i2
  i1 = i2
  i2 = sum
  print(sum)



1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
7540113804746346429
12

In [ ]:
def main():
  r = int(input("Enter the largest integer :"))
  s = int(input("Enter the size of the array:"))
  median(r,s)

def median(n , m):
  arr = np.random.randint(0,n,m)
  print(np.median(arr))

main()

Enter the largest integer :500
Enter the size of the array:50
265.0


In [ ]:
def main():
  i = int(input(" No of arguments"))
  mean(i)

def mean(n):
  arr = np.arange(n)
  print(np.mean(arr))

main()

 No of arguments100
49.5


In [ ]:
def main():
  d = int(input("No. of turns"))
  division(d)

def division(n):
  for i in range(n):
      if i == 0 :
         print("Not divisible")
      else :
         print(100/i)

main()


No. of turns5
Not divisible
100.0
50.0
33.333333333333336
25.0
